# Generated by Django 3.2.14 on 2023-06-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieArbolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
                ('nombre_cientifico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre cientifico')),
                ('nombre_vulgar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre vulgar')),
                ('nombre_completo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre completo')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
        migrations.CreateModel(
            name='ArbolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
                ('codigo_arbol', models.CharField(max_length=50)),
                ('altura', models.CharField(max_length=50)),
                ('dap', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=50)),
                ('longitud', models.CharField(max_length=50)),
                ('inclinacion', models.CharField(max_length=50)),
                ('estado_copa', models.CharField(max_length=50)),
                ('estado_tronco', models.CharField(max_length=50)),
                ('estado_raiz', models.CharField(max_length=50)),
                ('estado_plantera', models.CharField(max_length=50)),
                ('estado_vereda', models.CharField(max_length=50)),
                ('interferencias', models.CharField(max_length=50)),
                ('enfermedades', models.CharField(max_length=50)),
                ('riesgo', models.CharField(choices=[('', ''), ('1', 'Bajo'), ('2', 'Medio'), ('3', 'Alto')], default='', max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relevamiento.especiearbolmodel')),
            ],
            options={
                'verbose_name': 'Árbol',
                'verbose_name_plural': 'Árboles',
            },
        ),
    ]
