# Generated by Django 3.2 on 2023-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('calle', models.CharField(max_length=50, verbose_name='Calle')),
                ('numeracion', models.IntegerField(verbose_name='Numeración')),
                ('entre_calle_1', models.CharField(max_length=50, verbose_name='Entre calle')),
                ('entre_calle_2', models.CharField(max_length=50, verbose_name='y calle')),
                ('localidad', models.CharField(max_length=50, verbose_name='Localidad')),
                ('edificio', models.CharField(max_length=50, verbose_name='Edificio')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('especie', models.CharField(max_length=30, verbose_name='Especie')),
                ('altura', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Altura')),
            ],
        ),
        migrations.CreateModel(
            name='Denunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('telefono_fijo', models.IntegerField(verbose_name='Telefono fijo')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('medio', models.CharField(max_length=20, verbose_name='Medio')),
                ('fuente', models.CharField(choices=[('1', 'Oficina 1'), ('2', 'Oficina 2'), ('3', 'Oficina 3'), ('4', 'Oficina 4'), ('5', 'Oficina 5'), ('6', 'Oficina 6'), ('7', 'Oficina 7'), ('8', 'Oficina 8'), ('9', 'Oficina 9'), ('10', 'Oficina 10')], max_length=5, verbose_name='Fuente')),
                ('fecha', models.DateField(verbose_name='Fecha del reclamo')),
                ('reclamo', models.CharField(max_length=200, verbose_name='Reclamo')),
                ('urgencia', models.CharField(choices=[('0', 'Ninguna'), ('1', 'Baja'), ('2', 'Media'), ('3', 'Alta')], default='0', max_length=5, verbose_name='Urgencia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img_reclamos', verbose_name='Fotos')),
                ('detalle', models.CharField(max_length=500, verbose_name='Detalles')),
                ('reclamo_valido', models.BooleanField(default=0, verbose_name='Reclamo válido')),
                ('arboles', models.ManyToManyField(to='reclamos.Arbol', verbose_name='Arbol')),
                ('denunciantes', models.ManyToManyField(to='reclamos.Denunciante', verbose_name='Denunciante')),
            ],
        ),
    ]
