# Generated by Django 3.2.14 on 2023-06-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamomodel',
            options={'ordering': ['numero'], 'verbose_name': 'Reclamo', 'verbose_name_plural': 'Reclamos'},
        ),
    ]
