# Generated by Django 3.2.14 on 2023-06-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denunciantemodel',
            options={'verbose_name': 'Denunciante', 'verbose_name_plural': 'Denunciantes'},
        ),
        migrations.AlterModelOptions(
            name='reclamomodel',
            options={'verbose_name': 'Reclamo', 'verbose_name_plural': 'Reclamos'},
        ),
        migrations.AddField(
            model_name='reclamomodel',
            name='repitancia',
            field=models.IntegerField(default=1),
        ),
    ]
