# Generated by Django 3.2 on 2023-05-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='numero',
            field=models.CharField(max_length=25, verbose_name='Número'),
        ),
    ]
