# Generated by Django 3.2 on 2023-05-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arbol',
        ),
        migrations.RemoveField(
            model_name='reclamo',
            name='reclamo_valido',
        ),
        migrations.AddField(
            model_name='reclamo',
            name='calle',
            field=models.CharField(default='', max_length=50, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='departamento',
            field=models.CharField(default=0, max_length=50, verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='edificio',
            field=models.CharField(default=0, max_length=50, verbose_name='Edificio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='entre_calle_1',
            field=models.CharField(default='', max_length=50, verbose_name='Entre calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='entre_calle_2',
            field=models.CharField(default='', max_length=50, verbose_name='y calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='localidad',
            field=models.CharField(choices=[('', ''), ('1', '9 de Abril'), ('2', 'Canning'), ('3', 'El Jagüel'), ('4', 'Luis Guillón'), ('5', 'Monte Grande')], default='', max_length=50, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='numeracion',
            field=models.IntegerField(default=0, verbose_name='Numeración'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='arboles',
            field=models.ManyToManyField(to='inspeccion.Arbol', verbose_name='Arbol'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='fuente',
            field=models.CharField(choices=[('', ''), ('1', 'Arquitectura'), ('2', 'CAV'), ('3', 'Ceremonial'), ('4', 'COM'), ('5', 'Consejo Deliberante'), ('6', 'Consejo Escolar'), ('7', 'Cultura'), ('8', 'Defensa Civil'), ('9', 'Delegación 9 de Julio'), ('10', 'Delegación Canning'), ('11', 'Delegación El Jagüel'), ('12', 'Delegación Luis Guillón'), ('13', 'Delegación Malvinas'), ('14', 'Delegación Monte Grande Sur'), ('15', 'EDESUR S.A.'), ('16', 'Enlace Echeverría'), ('17', 'Entidades'), ('18', 'Espacios Verdes'), ('19', 'Gobierno'), ('20', 'Medio Ambiente'), ('21', 'Mesa de Entrada'), ('22', 'Obras Hídricas'), ('23', 'Obras Particulares'), ('24', 'Obras Públicas'), ('25', 'Prensa'), ('26', 'Seguridad'), ('27', 'Servicios'), ('28', 'Vecino')], default='', max_length=50, verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='medio',
            field=models.CharField(choices=[('', ''), ('06', 'Calle'), ('00', 'CAV'), ('01', 'Expediente'), ('07', 'Correo electrónico'), ('05', 'Nota'), ('03', 'Redes sociales'), ('04', 'Teléfono Oficina'), ('02', 'Ventanilla'), ('08', 'WAP')], default='', max_length=50, verbose_name='Medio'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='reclamo',
            field=models.CharField(choices=[('', ''), ('1', 'Árbol caído'), ('2', 'Árbol con riesgo de caída'), ('3', 'Árbol electrificado'), ('4', 'Corte de raíz'), ('5', 'Despeje de cables'), ('6', 'Despeje luminario'), ('7', 'Extracción'), ('8', 'Indemnización'), ('9', 'Panal de abejas/avispas'), ('10', 'Poda'), ('11', 'Poda sin autorización'), ('12', 'Queja'), ('13', 'Rama quebrada'), ('14', 'Recolección de poda'), ('15', 'Revisión de estado del árbol'), ('16', 'Solicitud de árbol'), ('17', 'Solicitud de autorización'), ('18', 'Tala sin autorización')], default='', max_length=200, verbose_name='Reclamo'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='urgencia',
            field=models.CharField(choices=[('', ''), ('1', 'Baja'), ('2', 'Media'), ('3', 'Alta')], default='', max_length=5, verbose_name='Urgencia'),
        ),
    ]
