# Generated by Django 3.2.14 on 2023-05-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denunciantemodel',
            name='fecha_edicion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AddField(
            model_name='reclamomodel',
            name='fecha_edicion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='denunciantemodel',
            name='telefono_fijo',
            field=models.IntegerField(verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='reclamomodel',
            name='localidad',
            field=models.CharField(choices=[('', ''), ('R2546787', '9 de Abril'), ('R2546804', 'Canning'), ('R2546834', 'El Jagüel'), ('R2546803', 'Luis Guillón'), ('R2546842', 'Monte Grande')], default='', max_length=50, verbose_name='Localidad'),
        ),
    ]
