from datetime import datetime
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotAllowed, JsonResponse
from django.template import loader
from gestion.forms import GesContacto, GesInspector, GesInspeccion, GesGestion

lista_reclamos = [
    {
		"medio": "1",
		"fuente": "1",
		"fecha": "01/01/0001",
		"nombre": "nombre 1",
		"apellido": "apellido 1",
		"dni": 1,
		"celular": 1,
		"tel_fijo": 1,
		"mail": "a@a.com",
		"calle": "calle 1",
		"altura": "altura 1",
		"edificio": "edificio 1",
		"departamento": "departamento 1",
		"entre_calle_1": "entre_calle_1 1",
		"entre_calle_2": "entre_calle_2 1",
		"localidad": "localidad 1",
		"urgencia": "urgencia 1",
		"detalle": "detalle 1",
		"nombre2": "nombre 1",
		"lugar": "lugar 1",
		"reclamo": 1,
		"nota": "nota 1",
		"numero_reclamo": 1,
		"reclamo_valido": True,
		"fecha_inspeccion": "01/01/0001",
		"trabajo": "trabajo 1",
		"especie": "especie 1",
		"altura3": "altura 1",
		"dap": "dap 1",
		"cableado": "cableado 1",
		"construccion": "construccion 1",
		"observaciones": "observaciones 1",
		"urgencia4": "urgencia 1",
		"inspector": "inspector 1",
		"estado": "estado 1",
		"gestion": "gestion 1",
		"detalle_gestion": "detalle_gestion 1",
		"equipo_trabajo": "equipo_trabajo 1",
		"fecha_programada": "01/01/0001",
		"fecha_solucion": "01/01/0001",
		"orden_trabajo": "orden_trabajo 1"
    },
    {
    	"Reclamo": "2",
    	"Medio": "Medio2",
    	"Fuente": "Fuente2",
    	"Fechadereclamo": "Fecha reclamo 2",
    	"NombreyApellido": "Nombre y apellido 2",
    	"DNI": "DNI 2",
    	"Celular": "Celular 2",
    	"Telefono": "Teléfono 2",
    	"Mail": "Mail 2",
    	"Calle": "Calle 2",
    	"Altura": "Altura 2",
    	"Edificio": "Edificio 2",
    	"Depto": "Depto 2",
    	"Entrecalle1": "EC 2-1",
    	"Entrecalle2": "EC 2-2",
    	"Localidad": "Localidad 2",
    	"ReclamoB": "ReclamoB 2",
    	"Urgencia": "Urgencia 2",
        "Detalledelreclamo": "Detalle 2",
    	"FechadeCarga": "Fecha Carga 2",
    	"ID": "ID 2",
    	"Norequiereinspeccion": "NRI 2",
    	"Fechadeinspeccion": "Fecha Insp 2",
    	"Trabajoarealizar": "Trabajo a ralizar 2",
    	"Especie": "Especie 2",
    	"Altura(m)": "Altura 2",
    	"Dap(cm)": "Dap 2",
    	"Cableadocercano": "Cableado 2",
    	"Construccioncercana": "Construccion 2",
    	"Observacionesdelsitio": "Obs 2",
    	"Urgenciadetrabajo": "Urgencia 2",
    	"Justificacion": "Justify 2",
    	"Inspector": "Boton 2",
    	"Fechadecarga de inspeccion": "Fecha carga 2",
    	"Codigotrabajo": "Cod trabajo 2",
    	"Lote": "Lote1 2",
    	"ESTADO": "Estado 2",
    	"Gestion": "Gestion 2",
    	"DetalledeGestion": "Detalle 2",
    	"EquipodeTrabajo": "Equipo Trabajo 2",
    	"FechaProgramada": "Fecha programada 2",
    	"FechadeSolucion": "Fecha Solucion 2",
    	"OrdendeTrabajo": "OT 2",
    },
    {
    	"Reclamo": "3",
    	"Medio": "Medio 3",
    	"Fuente": "Fuente 3",
    	"Fechadereclamo": "Fecha reclamo 3",
    	"NombreyApellido": "Nombre y apellido 3",
    	"DNI": "DNI 3",
    	"Celular": "Celular 3",
    	"Telefono": "Teléfono 3",
    	"Mail": "Mail 3",
    	"Calle": "Calle 3",
    	"Altura": "Altura 3",
    	"Edificio": "Edificio 3",
    	"Depto": "Depto 3",
    	"Entrecalle1": "EC 3-1",
    	"Entrecalle2": "EC 3-2",
    	"Localidad": "Localidad 3",
    	"ReclamoB": "ReclamoB 3",
    	"Urgencia": "Urgencia 3",
    	"Detalledelreclamo": "Detalle 3",
    	"FechadeCarga": "Fecha Carga 3",
    	"ID": "ID 3",
    	"Norequiereinspeccion": "NRI 3",
    	"Fechadeinspeccion": "Fecha Insp 3",
    	"Trabajoarealizar": "Trabajo a ralizar 3",
    	"Especie": "Especie 3",
    	"Altura(m)": "Altra 3",
    	"Dap(cm)": "Dap 3",
    	"Cableadocercano": "Cableado 3",
    	"Construccioncercana": "Construccion 3",
    	"Observacionesdelsitio": "Obs 3",
    	"Urgenciadetrabajo": "Urgencia 3",
    	"Justificacion": "Justify 3",
    	"Inspector": "Boton 3",
    	"Fechadecarga de inspeccion": "Fecha carga 3",
    	"Codigotrabajo": "Cod trabajo 3",
    	"Lote": "Lote 3",
    	"ESTADO": "Estado 3",
    	"Gestion": "Gestion 3",
    	"DetalledeGestion": "Detalle 3",
    	"EquipodeTrabajo": "Equipo Trabajo 3",
    	"FechaProgramada": "Fecha programada 3",
    	"FechadeSolucion": "Fecha Solucion 3",
    	"OrdendeTrabajo": "OT 3",
    },
    {
    	"Reclamo": "4",
    	"Medio": "Medio 4",
    	"Fuente": "Fuente 4",
    	"Fechadereclamo": "Fecha reclamo 4",
    	"NombreyApellido": "Nombre y apellido 4",
    	"DNI": "DNI 4",
    	"Celular": "Celular 4",
    	"Telefono": "Teléfono 4",
    	"Mail": "Mail 4",
    	"Calle": "Calle 4",
    	"Altura": "Altura 4",
    	"Edificio": "Edificio 4",
    	"Depto": "Depto 4",
    	"Entrecalle1": "EC 4-1",
    	"Entrecalle2": "EC 4-2",
    	"Localidad": "Localidad 4",
    	"ReclamoB": "ReclamoB 4",
    	"Urgencia": "Urgencia 4",
    	"Detalledelreclamo": "Detalle 4",
    	"FechadeCarga": "Fecha Carga 4",
    	"ID": "ID 4",
    	"Norequiereinspeccion": "NRI 4",
    	"Fechadeinspeccion": "Fecha Insp 4",
    	"Trabajoarealizar": "Trabajo a ralizar 4",
    	"Especie": "Especie 4",
    	"Altura(m)": "Altura 4",
    	"Dap(cm)": "Dap 4",
    	"Cableadocercano": "Cableado 4",
    	"Construccioncercana": "Construccion 4",
    	"Observacionesdelsitio": "Obs 4",
    	"Urgenciadetrabajo": "Urgencia 4",
    	"Justificacion": "Justify 4",
    	"Inspector": "Boton 4",
    	"Fechadecargadeinspeccion": "Fecha carga 4",
    	"Codigotrabajo": "Cod trabajo 4",
    	"Lote": "Lote 4",
    	"ESTADO": "Estado 4",
    	"Gestion": "Gestion 4",
    	"DetalledeGestion": "Detalle 4",
    	"EquipodeTrabajo": "Equipo Trabajo 4",
    	"FechaProgramada": "Fecha programada 4",
    	"FechadeSolucion": "Fecha Solucion 4",
    	"OrdendeTrabajo": "OT 4",
    },
    {
    	"Reclamo": "5",
    	"Medio": "Medio 5",
    	"Fuente": "Fuente 5",
    	"Fechadereclamo": "Fecha reclamo 5",
    	"NombreyApellido": "Nombre y apellido 5",
    	"DNI": "DNI 5",
    	"Celular": "Celular 5",
    	"Telefono": "Teléfono 5",
    	"Mail": "Mail 5",
    	"Calle": "Calle 5",
    	"Altura": "Altura 5",
    	"Edificio": "Edificio 5",
    	"Depto": "Depto 5",
    	"Entrecalle1": "EC 5-1",
    	"Entrecalle2": "EC 5-2",
    	"Localidad": "Localidad 5",
    	"ReclamoB": "ReclamoB 5",
    	"Urgencia": "Urgencia 5",
    	"Detalledelreclamo": "Detalle 5",
    	"FechadeCarga": "Fecha Carga 5",
    	"ID": "ID 5",
    	"Norequiereinspeccion": "NRI 5",
    	"Fechadeinspeccion": "Fecha Insp 5",
    	"Trabajoarealizar": "Trabajo a ralizar 5",
    	"Especie": "Especie 5",
    	"Altura(m)": "Altra 5",
    	"Dap(cm)": "Dap 5",
    	"Cableadocercano": "Cableado 5",
    	"Construccioncercana": "Construccion 5",
    	"Observacionesdelsitio": "Obs 5",
    	"Urgenciadetrabajo": "Urgencia 5",
    	"Justificacion": "Justify 5",
    	"Inspector": "Boton 5",
    	"Fechadecarga de inspeccion": "Fecha carga 5",
    	"Codigotrabajo": "Cod trabajo 5",
    	"Lote": "Lote 5",
    	"ESTADO": "Estado 5",
    	"Gestion": "Gestion 5",
    	"DetalledeGestion": "Detalle 5",
    	"EquipodeTrabajo": "Equipo Trabajo 5",
    	"FechaProgramada": "Fecha programada 5",
    	"FechadeSolucion": "Fecha Solucion 5",
    	"OrdendeTrabajo": "OT 5",
    }
]

lista_reclamos2 = [
 {
  "medio": "medio 1",
  "fuente": "fuente 1",
  "fecha": "fecha 1",
  "nombre": "nombre 1",
  "apellido": "apellido 1",
  "dni": "dni 1",
  "celular": "celular 1",
  "tel_fijo": "tel_fijo 1",
  "mail": "mail 1",
  "calle": "calle 1",
  "altura": "altura 1",
  "edificio": "edificio 1",
  "departamento": "departamento 1",
  "entre_calle_1": "entre_calle_1 1",
  "entre_calle_2": "entre_calle_2 1",
  "localidad": "localidad 1",
  "urgencia": "urgencia 1",
  "detalle": "detalle 1",
  "nombre2": "nombre 1",
  "lugar": "lugar 1",
  "reclamo": "reclamo 1",
  "nota": "nota 1",
  "numero_reclamo": "numero_reclamo 1",
  "reclamo_valido": "reclamo_valido 1",
  "fecha_inspeccion": "fecha_inspeccion 1",
  "trabajo": "trabajo 1",
  "especie": "especie 1",
  "altura3": "altura 1",
  "dap": "dap 1",
  "cableado": "cableado 1",
  "construccion": "construccion 1",
  "observaciones": "observaciones 1",
  "urgencia4": "urgencia 1",
  "inspector": "inspector 1",
  "estado": "estado 1",
  "gestion": "gestion 1",
  "detalle_gestion": "detalle_gestion 1",
  "equipo_trabajo": "equipo_trabajo 1",
  "fecha_programada": "fecha_programada 1",
  "fecha_solucion": "fecha_solucion 1",
  "orden_trabajo": "orden_trabajo 1"
 },
 {
  "medio": "medio 2",
  "fuente": "fuente 2",
  "fecha": "fecha 2",
  "nombre": "nombre 2",
  "apellido": "apellido 2",
  "dni": "dni 2",
  "celular": "celular 2",
  "tel_fijo": "tel_fijo 2",
  "mail": "mail 2",
  "calle": "calle 2",
  "altura": "altura 2",
  "edificio": "edificio 2",
  "departamento": "departamento 2",
  "entre_calle_1": "entre_calle_1 2",
  "entre_calle_2": "entre_calle_2 2",
  "localidad": "localidad 2",
  "urgencia": "urgencia 2",
  "detalle": "detalle 2",
  "nombre2": "nombre 2",
  "lugar": "lugar 2",
  "reclamo": "reclamo 2",
  "nota": "nota 2",
  "numero_reclamo": "numero_reclamo 2",
  "reclamo_valido": "reclamo_valido 2",
  "fecha_inspeccion": "fecha_inspeccion 2",
  "trabajo": "trabajo 2",
  "especie": "especie 2",
  "altura3": "altura 2",
  "dap": "dap 2",
  "cableado": "cableado 2",
  "construccion": "construccion 2",
  "observaciones": "observaciones 2",
  "urgencia4": "urgencia 2",
  "inspector": "inspector 2",
  "estado": "estado 2",
  "gestion": "gestion 2",
  "detalle_gestion": "detalle_gestion 2",
  "equipo_trabajo": "equipo_trabajo 2",
  "fecha_programada": "fecha_programada 2",
  "fecha_solucion": "fecha_solucion 2",
  "orden_trabajo": "orden_trabajo 2"
 },
 {
  "medio": "medio 3",
  "fuente": "fuente 3",
  "fecha": "fecha 3",
  "nombre": "nombre 3",
  "apellido": "apellido 3",
  "dni": "dni 3",
  "celular": "celular 3",
  "tel_fijo": "tel_fijo 3",
  "mail": "mail 3",
  "calle": "calle 3",
  "altura": "altura 3",
  "edificio": "edificio 3",
  "departamento": "departamento 3",
  "entre_calle_1": "entre_calle_1 3",
  "entre_calle_2": "entre_calle_2 3",
  "localidad": "localidad 3",
  "urgencia": "urgencia 3",
  "detalle": "detalle 3",
  "nombre2": "nombre 3",
  "lugar": "lugar 3",
  "reclamo": "reclamo 3",
  "nota": "nota 3",
  "numero_reclamo": "numero_reclamo 3",
  "reclamo_valido": "reclamo_valido 3",
  "fecha_inspeccion": "fecha_inspeccion 3",
  "trabajo": "trabajo 3",
  "especie": "especie 3",
  "altura3": "altura 3",
  "dap": "dap 3",
  "cableado": "cableado 3",
  "construccion": "construccion 3",
  "observaciones": "observaciones 3",
  "urgencia4": "urgencia 3",
  "inspector": "inspector 3",
  "estado": "estado 3",
  "gestion": "gestion 3",
  "detalle_gestion": "detalle_gestion 3",
  "equipo_trabajo": "equipo_trabajo 3",
  "fecha_programada": "fecha_programada 3",
  "fecha_solucion": "fecha_solucion 3",
  "orden_trabajo": "orden_trabajo 3"
 },
 {
  "medio": "medio 4",
  "fuente": "fuente 4",
  "fecha": "fecha 4",
  "nombre": "nombre 4",
  "apellido": "apellido 4",
  "dni": "dni 4",
  "celular": "celular 4",
  "tel_fijo": "tel_fijo 4",
  "mail": "mail 4",
  "calle": "calle 4",
  "altura": "altura 4",
  "edificio": "edificio 4",
  "departamento": "departamento 4",
  "entre_calle_1": "entre_calle_1 4",
  "entre_calle_2": "entre_calle_2 4",
  "localidad": "localidad 4",
  "urgencia": "urgencia 4",
  "detalle": "detalle 4",
  "nombre2": "nombre 4",
  "lugar": "lugar 4",
  "reclamo": "reclamo 4",
  "nota": "nota 4",
  "numero_reclamo": "numero_reclamo 4",
  "reclamo_valido": "reclamo_valido 4",
  "fecha_inspeccion": "fecha_inspeccion 4",
  "trabajo": "trabajo 4",
  "especie": "especie 4",
  "altura3": "altura 4",
  "dap": "dap 4",
  "cableado": "cableado 4",
  "construccion": "construccion 4",
  "observaciones": "observaciones 4",
  "urgencia4": "urgencia 4",
  "inspector": "inspector 4",
  "estado": "estado 4",
  "gestion": "gestion 4",
  "detalle_gestion": "detalle_gestion 4",
  "equipo_trabajo": "equipo_trabajo 4",
  "fecha_programada": "fecha_programada 4",
  "fecha_solucion": "fecha_solucion 4",
  "orden_trabajo": "orden_trabajo 4"
 },
 {
  "medio": "medio 5",
  "fuente": "fuente 5",
  "fecha": "fecha 5",
  "nombre": "nombre 5",
  "apellido": "apellido 5",
  "dni": "dni 5",
  "celular": "celular 5",
  "tel_fijo": "tel_fijo 5",
  "mail": "mail 5",
  "calle": "calle 5",
  "altura": "altura 5",
  "edificio": "edificio 5",
  "departamento": "departamento 5",
  "entre_calle_1": "entre_calle_1 5",
  "entre_calle_2": "entre_calle_2 5",
  "localidad": "localidad 5",
  "urgencia": "urgencia 5",
  "detalle": "detalle 5",
  "nombre2": "nombre 5",
  "lugar": "lugar 5",
  "reclamo": "reclamo 5",
  "nota": "nota 5",
  "numero_reclamo": "numero_reclamo 5",
  "reclamo_valido": "reclamo_valido 5",
  "fecha_inspeccion": "fecha_inspeccion 5",
  "trabajo": "trabajo 5",
  "especie": "especie 5",
  "altura3": "altura 5",
  "dap": "dap 5",
  "cableado": "cableado 5",
  "construccion": "construccion 5",
  "observaciones": "observaciones 5",
  "urgencia4": "urgencia 5",
  "inspector": "inspector 5",
  "estado": "estado 5",
  "gestion": "gestion 5",
  "detalle_gestion": "detalle_gestion 5",
  "equipo_trabajo": "equipo_trabajo 5",
  "fecha_programada": "fecha_programada 5",
  "fecha_solucion": "fecha_solucion 5",
  "orden_trabajo": "orden_trabajo 5"
 },
 {
  "medio": "medio 6",
  "fuente": "fuente 6",
  "fecha": "fecha 6",
  "nombre": "nombre 6",
  "apellido": "apellido 6",
  "dni": "dni 6",
  "celular": "celular 6",
  "tel_fijo": "tel_fijo 6",
  "mail": "mail 6",
  "calle": "calle 6",
  "altura": "altura 6",
  "edificio": "edificio 6",
  "departamento": "departamento 6",
  "entre_calle_1": "entre_calle_1 6",
  "entre_calle_2": "entre_calle_2 6",
  "localidad": "localidad 6",
  "urgencia": "urgencia 6",
  "detalle": "detalle 6",
  "nombre2": "nombre 6",
  "lugar": "lugar 6",
  "reclamo": "reclamo 6",
  "nota": "nota 6",
  "numero_reclamo": "numero_reclamo 6",
  "reclamo_valido": "reclamo_valido 6",
  "fecha_inspeccion": "fecha_inspeccion 6",
  "trabajo": "trabajo 6",
  "especie": "especie 6",
  "altura3": "altura 6",
  "dap": "dap 6",
  "cableado": "cableado 6",
  "construccion": "construccion 6",
  "observaciones": "observaciones 6",
  "urgencia4": "urgencia 6",
  "inspector": "inspector 6",
  "estado": "estado 6",
  "gestion": "gestion 6",
  "detalle_gestion": "detalle_gestion 6",
  "equipo_trabajo": "equipo_trabajo 6",
  "fecha_programada": "fecha_programada 6",
  "fecha_solucion": "fecha_solucion 6",
  "orden_trabajo": "orden_trabajo 6"
 },
 {
  "medio": "medio 7",
  "fuente": "fuente 7",
  "fecha": "fecha 7",
  "nombre": "nombre 7",
  "apellido": "apellido 7",
  "dni": "dni 7",
  "celular": "celular 7",
  "tel_fijo": "tel_fijo 7",
  "mail": "mail 7",
  "calle": "calle 7",
  "altura": "altura 7",
  "edificio": "edificio 7",
  "departamento": "departamento 7",
  "entre_calle_1": "entre_calle_1 7",
  "entre_calle_2": "entre_calle_2 7",
  "localidad": "localidad 7",
  "urgencia": "urgencia 7",
  "detalle": "detalle 7",
  "nombre2": "nombre 7",
  "lugar": "lugar 7",
  "reclamo": "reclamo 7",
  "nota": "nota 7",
  "numero_reclamo": "numero_reclamo 7",
  "reclamo_valido": "reclamo_valido 7",
  "fecha_inspeccion": "fecha_inspeccion 7",
  "trabajo": "trabajo 7",
  "especie": "especie 7",
  "altura3": "altura 7",
  "dap": "dap 7",
  "cableado": "cableado 7",
  "construccion": "construccion 7",
  "observaciones": "observaciones 7",
  "urgencia4": "urgencia 7",
  "inspector": "inspector 7",
  "estado": "estado 7",
  "gestion": "gestion 7",
  "detalle_gestion": "detalle_gestion 7",
  "equipo_trabajo": "equipo_trabajo 7",
  "fecha_programada": "fecha_programada 7",
  "fecha_solucion": "fecha_solucion 7",
  "orden_trabajo": "orden_trabajo 7"
 },
 {
  "medio": "medio 8",
  "fuente": "fuente 8",
  "fecha": "fecha 8",
  "nombre": "nombre 8",
  "apellido": "apellido 8",
  "dni": "dni 8",
  "celular": "celular 8",
  "tel_fijo": "tel_fijo 8",
  "mail": "mail 8",
  "calle": "calle 8",
  "altura": "altura 8",
  "edificio": "edificio 8",
  "departamento": "departamento 8",
  "entre_calle_1": "entre_calle_1 8",
  "entre_calle_2": "entre_calle_2 8",
  "localidad": "localidad 8",
  "urgencia": "urgencia 8",
  "detalle": "detalle 8",
  "nombre2": "nombre 8",
  "lugar": "lugar 8",
  "reclamo": "reclamo 8",
  "nota": "nota 8",
  "numero_reclamo": "numero_reclamo 8",
  "reclamo_valido": "reclamo_valido 8",
  "fecha_inspeccion": "fecha_inspeccion 8",
  "trabajo": "trabajo 8",
  "especie": "especie 8",
  "altura3": "altura 8",
  "dap": "dap 8",
  "cableado": "cableado 8",
  "construccion": "construccion 8",
  "observaciones": "observaciones 8",
  "urgencia4": "urgencia 8",
  "inspector": "inspector 8",
  "estado": "estado 8",
  "gestion": "gestion 8",
  "detalle_gestion": "detalle_gestion 8",
  "equipo_trabajo": "equipo_trabajo 8",
  "fecha_programada": "fecha_programada 8",
  "fecha_solucion": "fecha_solucion 8",
  "orden_trabajo": "orden_trabajo 8"
 },
 {
  "medio": "medio 9",
  "fuente": "fuente 9",
  "fecha": "fecha 9",
  "nombre": "nombre 9",
  "apellido": "apellido 9",
  "dni": "dni 9",
  "celular": "celular 9",
  "tel_fijo": "tel_fijo 9",
  "mail": "mail 9",
  "calle": "calle 9",
  "altura": "altura 9",
  "edificio": "edificio 9",
  "departamento": "departamento 9",
  "entre_calle_1": "entre_calle_1 9",
  "entre_calle_2": "entre_calle_2 9",
  "localidad": "localidad 9",
  "urgencia": "urgencia 9",
  "detalle": "detalle 9",
  "nombre2": "nombre 9",
  "lugar": "lugar 9",
  "reclamo": "reclamo 9",
  "nota": "nota 9",
  "numero_reclamo": "numero_reclamo 9",
  "reclamo_valido": "reclamo_valido 9",
  "fecha_inspeccion": "fecha_inspeccion 9",
  "trabajo": "trabajo 9",
  "especie": "especie 9",
  "altura3": "altura 9",
  "dap": "dap 9",
  "cableado": "cableado 9",
  "construccion": "construccion 9",
  "observaciones": "observaciones 9",
  "urgencia4": "urgencia 9",
  "inspector": "inspector 9",
  "estado": "estado 9",
  "gestion": "gestion 9",
  "detalle_gestion": "detalle_gestion 9",
  "equipo_trabajo": "equipo_trabajo 9",
  "fecha_programada": "fecha_programada 9",
  "fecha_solucion": "fecha_solucion 9",
  "orden_trabajo": "orden_trabajo 9"
 },
 {
  "medio": "medio 10",
  "fuente": "fuente 10",
  "fecha": "fecha 10",
  "nombre": "nombre 10",
  "apellido": "apellido 10",
  "dni": "dni 10",
  "celular": "celular 10",
  "tel_fijo": "tel_fijo 10",
  "mail": "mail 10",
  "calle": "calle 10",
  "altura": "altura 10",
  "edificio": "edificio 10",
  "departamento": "departamento 10",
  "entre_calle_1": "entre_calle_1 10",
  "entre_calle_2": "entre_calle_2 10",
  "localidad": "localidad 10",
  "urgencia": "urgencia 10",
  "detalle": "detalle 10",
  "nombre2": "nombre 10",
  "lugar": "lugar 10",
  "reclamo": "reclamo 10",
  "nota": "nota 10",
  "numero_reclamo": "numero_reclamo 10",
  "reclamo_valido": "reclamo_valido 10",
  "fecha_inspeccion": "fecha_inspeccion 10",
  "trabajo": "trabajo 10",
  "especie": "especie 10",
  "altura3": "altura 10",
  "dap": "dap 10",
  "cableado": "cableado 10",
  "construccion": "construccion 10",
  "observaciones": "observaciones 10",
  "urgencia4": "urgencia 10",
  "inspector": "inspector 10",
  "estado": "estado 10",
  "gestion": "gestion 10",
  "detalle_gestion": "detalle_gestion 10",
  "equipo_trabajo": "equipo_trabajo 10",
  "fecha_programada": "fecha_programada 10",
  "fecha_solucion": "fecha_solucion 10",
  "orden_trabajo": "orden_trabajo 10"
 },
 {
  "medio": "medio 11",
  "fuente": "fuente 11",
  "fecha": "fecha 11",
  "nombre": "nombre 11",
  "apellido": "apellido 11",
  "dni": "dni 11",
  "celular": "celular 11",
  "tel_fijo": "tel_fijo 11",
  "mail": "mail 11",
  "calle": "calle 11",
  "altura": "altura 11",
  "edificio": "edificio 11",
  "departamento": "departamento 11",
  "entre_calle_1": "entre_calle_1 11",
  "entre_calle_2": "entre_calle_2 11",
  "localidad": "localidad 11",
  "urgencia": "urgencia 11",
  "detalle": "detalle 11",
  "nombre2": "nombre 11",
  "lugar": "lugar 11",
  "reclamo": "reclamo 11",
  "nota": "nota 11",
  "numero_reclamo": "numero_reclamo 11",
  "reclamo_valido": "reclamo_valido 11",
  "fecha_inspeccion": "fecha_inspeccion 11",
  "trabajo": "trabajo 11",
  "especie": "especie 11",
  "altura3": "altura 11",
  "dap": "dap 11",
  "cableado": "cableado 11",
  "construccion": "construccion 11",
  "observaciones": "observaciones 11",
  "urgencia4": "urgencia 11",
  "inspector": "inspector 11",
  "estado": "estado 11",
  "gestion": "gestion 11",
  "detalle_gestion": "detalle_gestion 11",
  "equipo_trabajo": "equipo_trabajo 11",
  "fecha_programada": "fecha_programada 11",
  "fecha_solucion": "fecha_solucion 11",
  "orden_trabajo": "orden_trabajo 11"
 },
 {
  "medio": "medio 12",
  "fuente": "fuente 12",
  "fecha": "fecha 12",
  "nombre": "nombre 12",
  "apellido": "apellido 12",
  "dni": "dni 12",
  "celular": "celular 12",
  "tel_fijo": "tel_fijo 12",
  "mail": "mail 12",
  "calle": "calle 12",
  "altura": "altura 12",
  "edificio": "edificio 12",
  "departamento": "departamento 12",
  "entre_calle_1": "entre_calle_1 12",
  "entre_calle_2": "entre_calle_2 12",
  "localidad": "localidad 12",
  "urgencia": "urgencia 12",
  "detalle": "detalle 12",
  "nombre2": "nombre 12",
  "lugar": "lugar 12",
  "reclamo": "reclamo 12",
  "nota": "nota 12",
  "numero_reclamo": "numero_reclamo 12",
  "reclamo_valido": "reclamo_valido 12",
  "fecha_inspeccion": "fecha_inspeccion 12",
  "trabajo": "trabajo 12",
  "especie": "especie 12",
  "altura3": "altura 12",
  "dap": "dap 12",
  "cableado": "cableado 12",
  "construccion": "construccion 12",
  "observaciones": "observaciones 12",
  "urgencia4": "urgencia 12",
  "inspector": "inspector 12",
  "estado": "estado 12",
  "gestion": "gestion 12",
  "detalle_gestion": "detalle_gestion 12",
  "equipo_trabajo": "equipo_trabajo 12",
  "fecha_programada": "fecha_programada 12",
  "fecha_solucion": "fecha_solucion 12",
  "orden_trabajo": "orden_trabajo 12"
 },
 {
  "medio": "medio 13",
  "fuente": "fuente 13",
  "fecha": "fecha 13",
  "nombre": "nombre 13",
  "apellido": "apellido 13",
  "dni": "dni 13",
  "celular": "celular 13",
  "tel_fijo": "tel_fijo 13",
  "mail": "mail 13",
  "calle": "calle 13",
  "altura": "altura 13",
  "edificio": "edificio 13",
  "departamento": "departamento 13",
  "entre_calle_1": "entre_calle_1 13",
  "entre_calle_2": "entre_calle_2 13",
  "localidad": "localidad 13",
  "urgencia": "urgencia 13",
  "detalle": "detalle 13",
  "nombre2": "nombre 13",
  "lugar": "lugar 13",
  "reclamo": "reclamo 13",
  "nota": "nota 13",
  "numero_reclamo": "numero_reclamo 13",
  "reclamo_valido": "reclamo_valido 13",
  "fecha_inspeccion": "fecha_inspeccion 13",
  "trabajo": "trabajo 13",
  "especie": "especie 13",
  "altura3": "altura 13",
  "dap": "dap 13",
  "cableado": "cableado 13",
  "construccion": "construccion 13",
  "observaciones": "observaciones 13",
  "urgencia4": "urgencia 13",
  "inspector": "inspector 13",
  "estado": "estado 13",
  "gestion": "gestion 13",
  "detalle_gestion": "detalle_gestion 13",
  "equipo_trabajo": "equipo_trabajo 13",
  "fecha_programada": "fecha_programada 13",
  "fecha_solucion": "fecha_solucion 13",
  "orden_trabajo": "orden_trabajo 13"
 },
 {
  "medio": "medio 14",
  "fuente": "fuente 14",
  "fecha": "fecha 14",
  "nombre": "nombre 14",
  "apellido": "apellido 14",
  "dni": "dni 14",
  "celular": "celular 14",
  "tel_fijo": "tel_fijo 14",
  "mail": "mail 14",
  "calle": "calle 14",
  "altura": "altura 14",
  "edificio": "edificio 14",
  "departamento": "departamento 14",
  "entre_calle_1": "entre_calle_1 14",
  "entre_calle_2": "entre_calle_2 14",
  "localidad": "localidad 14",
  "urgencia": "urgencia 14",
  "detalle": "detalle 14",
  "nombre2": "nombre 14",
  "lugar": "lugar 14",
  "reclamo": "reclamo 14",
  "nota": "nota 14",
  "numero_reclamo": "numero_reclamo 14",
  "reclamo_valido": "reclamo_valido 14",
  "fecha_inspeccion": "fecha_inspeccion 14",
  "trabajo": "trabajo 14",
  "especie": "especie 14",
  "altura3": "altura 14",
  "dap": "dap 14",
  "cableado": "cableado 14",
  "construccion": "construccion 14",
  "observaciones": "observaciones 14",
  "urgencia4": "urgencia 14",
  "inspector": "inspector 14",
  "estado": "estado 14",
  "gestion": "gestion 14",
  "detalle_gestion": "detalle_gestion 14",
  "equipo_trabajo": "equipo_trabajo 14",
  "fecha_programada": "fecha_programada 14",
  "fecha_solucion": "fecha_solucion 14",
  "orden_trabajo": "orden_trabajo 14"
 },
 {
  "medio": "medio 15",
  "fuente": "fuente 15",
  "fecha": "fecha 15",
  "nombre": "nombre 15",
  "apellido": "apellido 15",
  "dni": "dni 15",
  "celular": "celular 15",
  "tel_fijo": "tel_fijo 15",
  "mail": "mail 15",
  "calle": "calle 15",
  "altura": "altura 15",
  "edificio": "edificio 15",
  "departamento": "departamento 15",
  "entre_calle_1": "entre_calle_1 15",
  "entre_calle_2": "entre_calle_2 15",
  "localidad": "localidad 15",
  "urgencia": "urgencia 15",
  "detalle": "detalle 15",
  "nombre2": "nombre 15",
  "lugar": "lugar 15",
  "reclamo": "reclamo 15",
  "nota": "nota 15",
  "numero_reclamo": "numero_reclamo 15",
  "reclamo_valido": "reclamo_valido 15",
  "fecha_inspeccion": "fecha_inspeccion 15",
  "trabajo": "trabajo 15",
  "especie": "especie 15",
  "altura3": "altura 15",
  "dap": "dap 15",
  "cableado": "cableado 15",
  "construccion": "construccion 15",
  "observaciones": "observaciones 15",
  "urgencia4": "urgencia 15",
  "inspector": "inspector 15",
  "estado": "estado 15",
  "gestion": "gestion 15",
  "detalle_gestion": "detalle_gestion 15",
  "equipo_trabajo": "equipo_trabajo 15",
  "fecha_programada": "fecha_programada 15",
  "fecha_solucion": "fecha_solucion 15",
  "orden_trabajo": "orden_trabajo 15"
 }
]

# Create your views here.
def gestion_inicio (request):  
    mensaje = None
    context = {
		'reclamos': lista_reclamos,
        'mensaje': mensaje
    }
    return render(request, 'gestion/gestion_inicio.html', context)


def gestion_editar_reclamo(request, nro_reclamo):
    mensaje = None
    if request.method == 'POST':
        form_contacto = GesContacto(request.POST)
        form_inspector = GesInspector(request.POST)
        form_inspeccion = GesInspeccion(request.POST)
        form_gestion = GesGestion(request.POST)
        mensaje = 'Hemos recibido tus datos'
        # acción para tomar los datos del formulario
    elif request.method == 'GET':
        form_contacto = GesContacto(lista_reclamos[nro_reclamo-1])
        form_inspector = GesInspector(lista_reclamos[nro_reclamo-1])
        form_inspeccion = GesInspeccion(lista_reclamos[nro_reclamo-1])
        form_gestion = GesGestion(lista_reclamos[nro_reclamo-1])
    else:
        return HttpResponseNotAllowed(f"Método {request.method} no soportado")

    context = {
        'nro_reclamo' : nro_reclamo,
        'mensaje': mensaje,
        'reclamo': lista_reclamos[nro_reclamo-1],
        'form_contacto': form_contacto,
        'form_inspector': form_inspector,
        'form_inspeccion': form_inspeccion,
        'form_gestion': form_gestion,
    }
    return render(request, 'gestion/gestion_editar_reclamo.html', context)
