# Generated by Django 3.2.14 on 2023-06-15 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('punto1_lat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_1_latitud')),
                ('punto1_long', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_1_longitud')),
                ('punto2_lat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_2_latitud')),
                ('punto2_long', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_2_longitud')),
                ('punto3_lat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_3_latitud')),
                ('punto3_long', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_3_longitud')),
                ('punto4_lat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_4_latitud')),
                ('punto4_long', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_4_longitud')),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(verbose_name='Fecha_alta')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=30, verbose_name='Razon_social')),
                ('num_proveedor', models.IntegerField(verbose_name='Num_proveedor')),
                ('cuit', models.IntegerField(verbose_name='Cuit')),
                ('correo', models.EmailField(max_length=20, verbose_name='Correo_Electronico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('orden_compra', models.IntegerField(null=True, verbose_name='OC')),
                ('eliminado', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('usuario', models.CharField(max_length=15, verbose_name='Usuario')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave')),
                ('permiso', models.CharField(max_length=20, verbose_name='Permiso')),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(verbose_name='Fecha_emision')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cantidad')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio_unitario')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('certificacion_cant', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Certificacion_cantidad')),
                ('certificacion_monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Certificacion_monto')),
                ('saldo_cant', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Saldo_cantidad')),
                ('saldo_monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo_monto')),
                ('eliminado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
