# Generated by Django 3.2 on 2023-05-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha_emision'),
        ),
    ]
