# Generated by Django 3.2 on 2023-06-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='legajo',
            field=models.CharField(default='', max_length=10, verbose_name='Legajo'),
            preserve_default=False,
        ),
    ]
