# Generated by Django 3.2 on 2023-05-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Gestor',
        ),
        migrations.DeleteModel(
            name='Inspector',
        ),
        migrations.DeleteModel(
            name='Operador',
        ),
    ]
