# Generated by Django 3.2 on 2023-05-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_ordencompra_fecha_emision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('usuario', models.CharField(max_length=15, verbose_name='Usuario')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave')),
                ('permiso', models.CharField(max_length=20, verbose_name='Permiso')),
                ('eliminado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_emision',
            field=models.DateField(verbose_name='Fecha_emision'),
        ),
    ]
