# Generated by Django 3.2 on 2023-05-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha_alta')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=30, verbose_name='Razon_social')),
                ('num_proveedor', models.IntegerField(max_length=15, verbose_name='Num_proveedor')),
                ('cuit', models.IntegerField(verbose_name='Cuit')),
                ('correo', models.EmailField(max_length=20, verbose_name='Correo_Electronico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha_emision')),
                ('empresa', models.CharField(max_length=30, verbose_name='Empresa')),
                ('numero', models.IntegerField(max_length=20, verbose_name='Numero')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cantidad')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio_unitario')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('certificacion_cant', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Certificacion_cantidad')),
                ('certificacion_monto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='CErtificacion_monto')),
                ('saldo_cant', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Saldo_cantidad')),
                ('saldo_monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo_monto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
