# Generated by Django 3.2 on 2023-05-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_empresa_ordencompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('punto1_lat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_1_latitud')),
                ('punto1_long', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_1_longitud')),
                ('punto2_lat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_2_latitud')),
                ('punto2_long', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_2_longitud')),
                ('punto3_lat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_3_latitud')),
                ('punto3_long', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_3_longitud')),
                ('punto4_lat', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_4_latitud')),
                ('punto4_long', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Punto_4_longitud')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='orden_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.CharField(default='', max_length=30, verbose_name='Proveedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='num_proveedor',
            field=models.IntegerField(verbose_name='Num_proveedor'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero',
            field=models.IntegerField(verbose_name='Numero'),
        ),
    ]
