# Generated by Django 3.2 on 2023-05-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_auto_20230515_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrante',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='orden_compra',
            field=models.IntegerField(verbose_name='OC'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa', verbose_name='Proveedor'),
        ),
    ]
