# Generated by Django 3.2 on 2023-05-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20230518_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='empresa',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
