# Generated by Django 3.2 on 2023-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspeccion',
            options={},
        ),
        migrations.RemoveField(
            model_name='arbol',
            name='urgencia',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='reclamo',
        ),
        migrations.RemoveField(
            model_name='inspeccion',
            name='trabajo',
        ),
        migrations.AlterField(
            model_name='inspecciones',
            name='urgencia_trabajo',
            field=models.CharField(choices=[('BLANK ', ' '), ('BAJA', 'BAJA'), ('MEDIA', 'MEDIA'), ('ALTA', 'ALTA')], default='', max_length=10, verbose_name='Urgencia'),
        ),
        migrations.AlterModelTable(
            name='inspeccion',
            table=None,
        ),
    ]
