# Generated by Django 3.2.14 on 2023-05-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspeccion',
            options={'ordering': ['fecha_inspeccion', 'lugar', 'reclamo'], 'verbose_name': 'Inspeccion', 'verbose_name_plural': 'Inspecciones'},
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='fecha_inspeccion',
            field=models.DateField(default=None, verbose_name='Fecha de inspección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='lugar',
            field=models.CharField(choices=[('ZE', 'Zona geográfica Este'), ('ZO', 'Zona geográfica Oeste'), ('ZN', 'Zona geográfica Norte'), ('ZS', 'Zona geográfica Sur')], default='ZN', max_length=2),
        ),
        migrations.AlterModelTable(
            name='inspeccion',
            table='inspeccion',
        ),
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reclamo_nombre', models.CharField(choices=[(22, '00-283706-01 Arbol caido'), (21, '01-293934-02 Arbol poda'), (19, '00-297349-01 Arbol enfermo')], max_length=50)),
                ('trabajo', models.CharField(choices=[(1, ''), (2, 'Poda integral 1'), (3, 'Poda integral 2'), (4, 'Poda integral 3'), (5, 'Poda reductiva 1'), (6, 'Poda reductiva 2'), (7, 'Poda reductiva 4'), (8, 'Tala'), (9, 'Extracción'), (10, 'Corte de raices')], max_length=20)),
                ('inspeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspeccion.inspeccion')),
            ],
        ),
    ]
