# Generated by Django 3.2 on 2023-05-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='observaciones_sitio',
            field=models.CharField(default='', max_length=50, verbose_name='Observaciones'),
        ),
    ]
