# Generated by Django 3.2 on 2023-05-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecciones',
            name='arbol',
        ),
        migrations.RemoveField(
            model_name='inspecciones',
            name='cableado_cercano',
        ),
        migrations.RemoveField(
            model_name='inspecciones',
            name='codigo_trabajo',
        ),
        migrations.RemoveField(
            model_name='inspecciones',
            name='construccion_cercana',
        ),
        migrations.RemoveField(
            model_name='inspecciones',
            name='fecha_carga_inspeccion',
        ),
        migrations.RemoveField(
            model_name='inspecciones',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='inspecciones',
            name='justificacion',
        ),
        migrations.RemoveField(
            model_name='inspecciones',
            name='observaciones_sitio',
        ),
        migrations.RemoveField(
            model_name='inspecciones',
            name='urgencia_trabajo',
        ),
        migrations.AddField(
            model_name='inspecciones',
            name='disposicion',
            field=models.CharField(default='', max_length=20, verbose_name='Disposicion'),
        ),
    ]
