# Generated by Django 3.2 on 2023-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0002_alter_inspecciones_observaciones_sitio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='cableado_cercano',
            field=models.CharField(default='', max_length=50, verbose_name='Cableado_cercano'),
        ),
    ]
