# Generated by Django 3.2.14 on 2023-06-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0002_auto_20230604_1157'),
        ('inspeccion', '0002_auto_20230611_1327'),
    ]

    operations = [
    ]
