# Generated by Django 3.2.14 on 2023-05-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0002_auto_20230528_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbol',
            name='reclamo_nombre',
        ),
        migrations.RemoveField(
            model_name='arbol',
            name='trabajo',
        ),
        migrations.AddField(
            model_name='arbol',
            name='urgencia',
            field=models.CharField(choices=[('01', ''), ('02', 'Alta'), ('03', 'Media'), ('04', 'Baja')], default='1', max_length=12),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='especie',
            field=models.CharField(choices=[('01', ''), ('02', 'jacaranda'), ('03', 'ceibo'), ('04', 'lapacho')], default='1', max_length=20, verbose_name='Especie'),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='trabajo',
            field=models.CharField(choices=[('01', ''), ('02', 'Poda integral 1'), ('03', 'Poda integral 2'), ('04', 'Poda integral 3'), ('05', 'Poda reductiva 1'), ('06', 'Poda reductiva 2'), ('07', 'Poda reductiva 4'), ('08', 'Tala'), ('09', 'Extracción'), ('10', 'Corte de raices')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='inspector',
            field=models.CharField(choices=[('01', ''), ('02', 'Pep Guardiola'), ('03', 'Miguel conejito Alejandro'), ('04', 'Angela Merkel')], default='01', max_length=25, verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='nota',
            field=models.CharField(blank=True, max_length=300, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='reclamo',
            field=models.CharField(choices=[('01', ''), ('02', '00-283706-01 Arbol caido'), ('03', '01-293934-02 Arbol poda'), ('04', '00-297349-01 Arbol enfermo')], default='01', max_length=100, verbose_name='Reclamo a inspeccionar'),
        ),
    ]
