# Generated by Django 3.2.14 on 2023-05-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0003_auto_20230528_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='urgencia',
            field=models.CharField(choices=[('01', ''), ('Alta', '02'), ('Media', 'Media'), ('Baja', 'Baja')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='especie',
            field=models.CharField(choices=[('01', ''), ('jacaranda', '02'), ('ceibo', '03'), ('lapacho', '04')], default='1', max_length=100, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='inspector',
            field=models.CharField(choices=[('01', ''), ('Pepe Guardiola', '02'), ('Miguel conejito Alejandro', '03'), ('Angela Merkel', '04')], default='01', max_length=100, verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='lugar',
            field=models.CharField(choices=[('Zona Este', '01'), ('Zona Oeste', '02'), ('Zona Norte', '03'), ('Zona Sur', '04')], default='ZN', max_length=100),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='reclamo',
            field=models.CharField(choices=[('01', ''), ('00-283706-01 Arbol caido', '02'), ('01-293934-02 Arbol poda', '03'), ('00-297349-01 Arbol enfermo', '04')], default='01', max_length=100, verbose_name='Reclamo a inspeccionar'),
        ),
        migrations.AlterField(
            model_name='inspeccion',
            name='trabajo',
            field=models.CharField(choices=[('01', ''), ('Poda integral 1', '02'), ('Poda integral 2', '03'), ('Poda integral 3', '04'), ('Poda reductiva 1', '05'), ('Poda reductiva 2', 'Poda reductiva 2'), ('Poda reductiva 3', 'Poda reductiva 3'), ('Talar', 'Tala'), ('Extraccion', 'Extracción'), ('Corte de raices', 'Corte de raices')], default='1', max_length=100),
        ),
    ]
