# Generated by Django 3.2.14 on 2023-06-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0003_merge_0002_auto_20230604_1157_0002_auto_20230611_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecciones',
            name='repitancia',
            field=models.IntegerField(default=0, verbose_name='repitancia', null=True),
            preserve_default=False,
        ),
    ]
