# Generated by Django 3.2.14 on 2023-06-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0004_inspecciones_repitancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='repitancia',
            field=models.CharField(verbose_name='repitancia',null=True),
        ),
    ]
