# Generated by Django 3.2 on 2023-05-26 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0004_auto_20230525_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vulgar', models.CharField(default='', max_length=50, verbose_name='Nombre_vulgar')),
                ('nombre_cientifico', models.CharField(default='', max_length=50, verbose_name='Nombre_cientifico')),
                ('nombre_completo', models.CharField(default='', max_length=50, verbose_name='Nombre_completo')),
            ],
        ),
        migrations.AddField(
            model_name='inspecciones',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspeccion.especies', verbose_name='trabajos'),
        ),
    ]
