# Generated by Django 3.2 on 2023-05-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0005_auto_20230526_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='especie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inspeccion.especies', verbose_name='Especie'),
        ),
    ]
