# Generated by Django 3.2.14 on 2023-06-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0005_alter_inspecciones_repitancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='repitancia',
            field=models.IntegerField(default=0, verbose_name='repitancia',null=True),
            preserve_default=False,
        ),
    ]
