# Generated by Django 3.2.14 on 2023-06-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0006_alter_inspecciones_repitancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='repitancia',
            field=models.IntegerField(verbose_name='repitancia'),
        ),
    ]
