# Generated by Django 3.2 on 2023-05-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('inspeccion', '0007_auto_20230526_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspecciones',
            name='inspector',
        ),
        migrations.AddField(
            model_name='inspecciones',
            name='inspector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario', verbose_name='inspector'),
            preserve_default=False,
        ),
    ]
