# Generated by Django 3.2.14 on 2023-06-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0007_alter_inspecciones_repitancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='repitancia',
            field=models.CharField(default='', max_length=5, null=True, verbose_name='repitancia'),
        ),
    ]
