# Generated by Django 3.2 on 2023-05-26 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0003_alter_reclamo_detalle'),
        ('inspeccion', '0008_auto_20230526_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reclamos.reclamo', verbose_name='Reclamo'),
        ),
    ]
