# Generated by Django 3.2.14 on 2023-06-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0008_alter_inspecciones_repitancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Fotos'),
        ),
    ]
