# Generated by Django 3.2 on 2023-05-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0011_alter_inspecciones_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecciones',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_inspecciones', verbose_name='Fotos'),
        ),
    ]
