# Generated by Django 3.2 on 2023-05-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0012_inspecciones_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspecciones',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_reclamos', verbose_name='Fotos'),
        ),
    ]
