# Generated by Django 3.2.14 on 2023-05-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('', ''), ('A', 'Estado A'), ('B', 'Estado B'), ('C', 'Estado C'), ('D', 'Estado D')], default='', max_length=30, verbose_name='Estado')),
                ('gestion', models.CharField(max_length=30, verbose_name='Gestión')),
                ('detalle_gestion', models.CharField(max_length=250, verbose_name='Detalle de gestión')),
                ('equipo_trabajo', models.CharField(max_length=30, verbose_name='Equipo de trabajo')),
                ('fecha_programada', models.DateField(auto_now_add=True, verbose_name='Fecha programada')),
                ('fecha_solucion', models.DateField(auto_now_add=True, verbose_name='Fecha de solución')),
                ('orden_trabajo', models.CharField(max_length=30, verbose_name='Orden de trabajo')),
                ('arbol', models.CharField(max_length=30, verbose_name='Arbol')),
                ('baja', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
