# Generated by Django 3.2.14 on 2023-06-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('', ''), ('A', 'Estado A'), ('B', 'Estado B'), ('C', 'Estado C'), ('D', 'Estado D')], default='', max_length=30, verbose_name='Estado')),
                ('gestion', models.CharField(max_length=30, verbose_name='Gestión')),
                ('detalle_gestion', models.CharField(max_length=250, verbose_name='Detalle de gestión')),
                ('equipo_trabajo', models.CharField(max_length=30, verbose_name='Equipo de trabajo')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('fecha_solucion', models.DateField(verbose_name='Fecha de solución')),
                ('orden_trabajo', models.CharField(max_length=30, verbose_name='Orden de trabajo')),
                ('arbol', models.CharField(max_length=30, verbose_name='Arbol')),
                ('eliminado', models.BooleanField(default=False)),
                ('inspecciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspeccion.inspecciones')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
