# Generated by Django 3.2.14 on 2023-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='fecha_programada',
            field=models.DateField(verbose_name='Fecha programada'),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='fecha_solucion',
            field=models.DateField(verbose_name='Fecha de solución'),
        ),
    ]
