# Generated by Django 3.2.14 on 2023-06-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gestion',
            new_name='GestionModel',
        ),
    ]
