# Generated by Django 3.2.14 on 2023-06-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
        ('gestion', '0002_rename_gestion_gestionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gestionmodel',
            old_name='baja',
            new_name='eliminado',
        ),
        migrations.AddField(
            model_name='gestionmodel',
            name='inspecciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspeccion.inspecciones'),
        ),
    ]
